#!/usr/bin/env bash
set -e

# Disable buffering for Verilator to ensure printfs and local println
# from the test harness are properly sequenced.
export VERILATOR_FLAGS="${VERILATOR_FLAGS} --autoflush"

scala_args=()

for arg in "$@"; do
  case "$arg" in
    --wave)
      scala_args+=("-DemitVcd=1" "-DfirtoolOpts=-g")
      ;;
    *)
      scala_args+=("-z" "$arg")
      ;;
  esac
done

if [[ ${#scala_args[@]} -gt 0 ]]; then
  scala-cli test hardware -- "${scala_args[@]}"
else
  scala-cli test hardware
fi
